[package]
name = "ia"
authors = ["CowboyAI"]
description = "Information Alchemist - AI-Powered Graph Editor"
version = "0.1.0"
edition = "2024"
exclude = ["examples/"]

[lints.clippy]
all = { level = "warn", priority = -1 }

# The following ensures clippy ignores examples
# through Cargo's workspace inheritance
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace]
exclude = ["examples/"]

[features]
default = []
dev = [
  "bevy/asset_processor",
  "bevy/file_watcher",
  "bevy/dynamic_linking"
]
integration-tests = []

[dependencies]
rand = "0.9"
egui = "0.31.1"
eframe = "0.31.1"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
egui-snarl = "0.7.1"
bevy = { version = "0.16.1", default-features = false, features = [
  # Core features
  "bevy_asset",
  "bevy_audio",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_gilrs",
  "bevy_gizmos",
  "bevy_gltf",
  "bevy_pbr",
  "bevy_picking",
  "bevy_render",
  "bevy_scene",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "bevy_window",
  "bevy_winit",
  "bevy_state",
  "bevy_input_focus",
  "bevy_log",

  # Picking backends
  "bevy_mesh_picking_backend",
  "bevy_sprite_picking_backend",
  "bevy_ui_picking_backend",

  # Image formats
  "png",
  "hdr",

  # Audio formats
  "vorbis",

  # Platform features
  "x11",
  "wayland",

  # Other essential features
  "multi_threaded",
  "default_font",
  "tonemapping_luts",
  "smaa_luts",
  "animation",
  "custom_cursor",
  "sysinfo_plugin",
  "android_shared_stdcxx",
  "android-game-activity",
  "async_executor",
  "std",

  # Explicitly NOT including webgl2 which can cause issues
] }
bevy_egui = "0.34.1"
rand_chacha = "0.9.0"
petgraph = { version = "0.8.1", features = ["serde-1"] }
daggy = { version = "0.9.0", features = ["serde-1"] }

[lib]
name = "ia"
path = "src/lib.rs"

[[bin]]
name = "ia"
path = "src/main.rs"
