[package]
name = "ia"
authors = ["CowboyAI"]
description = "Information Alchemist - AI-Powered Graph Editor"
version = "0.1.0"
edition = "2024"
exclude = ["examples/"]

[lints.clippy]
all = { level = "warn", priority = -1 }

# The following ensures clippy ignores examples
# through Cargo's workspace inheritance
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace]
exclude = ["examples/", "cim-ipld/"]

[features]
default = []
dynamic = ["bevy/dynamic_linking"]
dev = [
  "bevy/asset_processor",
  "bevy/file_watcher",
  "dynamic"
]
integration-tests = []

[dependencies]
# Core dependencies
rand = "0.9"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bevy = { version = "0.16.1", features = ["wayland"] }

# Graph library
petgraph = { version = "0.8.1", features = ["serde-1"] }
daggy = { version = "0.9.0", features = ["serde-1"] }

# Async runtime
tokio = { version = "1.42", features = ["full"] }
async-trait = "0.1"

# NATS messaging
async-nats = { version = "0.41", features = ["service"] }

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Utilities
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Content addressing
cim-ipld = { path = "cim-ipld" }
cid = "0.11"
multihash = { version = "0.19", features = ["std"] }
blake3 = "1.5"

# Channel implementations
crossbeam-channel = "0.5"
futures = "0.3"

# Caching
lru = "0.12"

# Time handling
time = { version = "0.3", features = ["serde", "formatting"] }

# Compression
zstd = "0.13"

# Bytes handling
bytes = "1.5"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
strip = true

[lib]
name = "ia"
path = "src/lib.rs"

[[bin]]
name = "ia"
path = "src/main.rs"
