[package]
name = "ia"
authors = ["CowboyAI"]
description = "Information Alchemist - AI-Powered Graph Editor"
version = "0.1.0"
edition = "2024"
exclude = ["examples/"]

[lints.clippy]
all = { level = "warn", priority = -1 }

# The following ensures clippy ignores examples
# through Cargo's workspace inheritance
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace]
exclude = ["examples/"]

[features]
default = []
dev = [
  "bevy/asset_processor",
  "bevy/file_watcher",
  "bevy/dynamic_linking"
]
integration-tests = []

[dependencies]
rand = "0.9"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bevy = "0.16.1"
rand_chacha = "0.9.0"
petgraph = { version = "0.8.1", features = ["serde-1"] }
daggy = { version = "0.9.0", features = ["serde-1"] }
rfd = "0.15"

[dev-dependencies]
tempfile = "3.14"

[lib]
name = "ia"
path = "src/lib.rs"

[[bin]]
name = "ia"
path = "src/main.rs"

# Patch Bevy crates to use our local version with experimental features removed
[patch.crates-io]
bevy = { path = "./bevy-patched" }
bevy_render = { path = "./bevy-patched/crates/bevy_render" }
bevy_core_pipeline = { path = "./bevy-patched/crates/bevy_core_pipeline" }
bevy_pbr = { path = "./bevy-patched/crates/bevy_pbr" }
bevy_ecs = { path = "./bevy-patched/crates/bevy_ecs" }
bevy_ecs_macros = { path = "./bevy-patched/crates/bevy_ecs/macros" }
