[package]
name = "alchemist"
authors = ["CowboyAI"]
description = "Information alchemy UI"
version = "0.1.0"
edition = "2021"
exclude = ["examples/"]

[lints.clippy]
all = { level = "warn", priority = -1 }

# The following ensures clippy ignores examples
# through Cargo's workspace inheritance
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace]
exclude = ["examples/"]

[dependencies]
rand = "0.9"
egui = "0.31.1"
eframe = "0.31.1"
uuid = { version = "1.4", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
egui-snarl = "0.7.1"
bevy = { version = "0.16.0", features = [
  "dynamic_linking",
  "jpeg",
  "animation",
  "multi_threaded",
  "bevy_render",
  "bevy_core_pipeline",
  "x11",
  "wayland",
] }
bevy_egui = "0.34.1"
rand_chacha = "0.9.0"
bevy_panorbit_camera = "0.26.0"
petgraph = { version = "0.6", features = ["serde-1"] }
daggy = { version = "0.8", features = ["serde-1"] }
