[package]
name = "alchemist"
authors = ["CowboyAI"]
description = "Information alchemy UI"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9"
egui = "0.31.1"
eframe = "0.31.1"
uuid = { version = "1.4", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
egui-snarl = "0.7.1"
