[package]
name = "ia"
authors = ["CowboyAI"]
description = "Information Alchemist - AI-Powered Graph Editor"
version = "0.1.0"
edition = "2024"
exclude = ["examples/"]

[lints.clippy]
all = { level = "warn", priority = -1 }

# The following ensures clippy ignores examples
# through Cargo's workspace inheritance
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace]
exclude = ["examples/"]

[features]
default = []
dev = [
  "bevy/asset_processor",
  "bevy/file_watcher"
]

[dependencies]
rand = "0.9"
egui = "0.31.1"
eframe = "0.31.1"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
egui-snarl = "0.7.1"
bevy = { version = "0.16.0", features = [
  "jpeg",
  "animation",
  "multi_threaded",
  "bevy_render",
  "bevy_core_pipeline",
  "x11",
  "wayland",
] }
bevy_egui = "0.34.1"
rand_chacha = "0.9.0"
bevy_panorbit_camera = "0.26.0"
petgraph = { version = "0.8.1", features = ["serde-1"] }
daggy = { version = "0.9.0", features = ["serde-1"] }

[lib]
name = "ia"
path = "src/lib.rs"

[[bin]]
name = "ia"
path = "src/main.rs"

[[bin]]
name = "verify_storage"
path = "src/bin/verify_storage.rs"
