name: Feature Request
description: Suggest a new feature or enhancement for Information Alchemist
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We follow Domain-Driven Design principles, so please help us understand both the business value and technical implementation.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason/benefit].
        
        Currently, users have to [current workaround/limitation]...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: |
        I would like [detailed description of the solution]...
        
        This would work by [explanation of how it works]...
    validations:
      required: true

  - type: dropdown
    id: domain-context
    attributes:
      label: Primary Domain Context
      description: Which domain would this feature primarily belong to?
      options:
        - Graph Visualization (cim-domain-graph)
        - Agent Management (cim-domain-agent) 
        - Conceptual Spaces (cim-domain-conceptualspaces)
        - Document Management (cim-domain-document)
        - Git Integration (cim-domain-git)
        - NIX Integration (cim-domain-nix)
        - Policy Management (cim-domain-policy)
        - Workflow Management (cim-domain-workflow)
        - Infrastructure (cim-infrastructure)
        - Presentation Layer (Bevy UI)
        - NATS Messaging
        - Cross-Domain Feature
        - New Domain Needed
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Domain Aggregate
        - New Domain Event
        - New Command/Query
        - UI/UX Enhancement
        - Performance Optimization
        - Integration Feature
        - Developer Tooling
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: domain-events
    attributes:
      label: Domain Events
      description: |
        What domain events would this feature generate? (Use past tense, e.g., "NodeCreated", "GraphPublished")
      placeholder: |
        - FeatureActivated
        - ConfigurationChanged
        - ProcessCompleted
        
        These events would be published to: [NATS subject pattern]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define what "done" looks like for this feature. Use concrete, testable criteria.
      placeholder: |
        - [ ] User can [specific action]
        - [ ] System responds with [specific behavior]
        - [ ] Events are published to [specific subject]
        - [ ] Feature is documented in [location]
        - [ ] Tests cover [specific scenarios]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: |
        Alternative 1: [description and why it's not ideal]
        Alternative 2: [description and why it's not ideal]

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (minor change to existing code)
        - Medium (new components/systems required)
        - High (new domain or major architectural change)
        - Unknown (needs investigation)

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (significant improvement)
        - Medium (nice to have)
        - Low (eventual enhancement)

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: |
        Provide detailed user stories for this feature
      placeholder: |
        **Story 1: Basic Usage**
        As a [user type], I want to [action] so that [benefit].
        
        **Story 2: Advanced Usage**
        As a [user type], I want to [action] so that [benefit].
        
        **Story 3: Error Handling**
        As a [user type], when [error condition], I want [behavior] so that [benefit].

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: |
        Any technical constraints, dependencies, or implementation notes?
      placeholder: |
        - Dependencies on [other features/systems]
        - Performance considerations: [details]
        - Security implications: [details]
        - Breaking changes: [yes/no and details]

  - type: checkboxes
    id: contribution-willingness
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to implement this feature myself
          required: false
        - label: I can help with testing and validation
          required: false
        - label: I can help with documentation
          required: false
        - label: I can provide domain expertise
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this feature request, you agree to our terms
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
        - label: This feature aligns with the project's goals and architecture
          required: true 