apiVersion: v1
kind: ConfigMap
metadata:
  name: alchemist-config
  namespace: alchemist
  labels:
    app: alchemist
    component: config
data:
  config.yaml: |
    agent:
      id: "alchemist-k8s-${POD_NAME}"
      name: "CIM Alchemist Kubernetes"
      description: "Production AI agent for CIM architecture on Kubernetes"
      cluster_mode: true
      instance_id: "${POD_NAME}"

    model_provider:
      type: "${AI_PROVIDER}"
      anthropic:
        base_url: "https://api.anthropic.com/v1"
        api_key: "${ANTHROPIC_API_KEY}"
        model: "claude-3-opus-20240229"
        options:
          temperature: 0.5
          max_tokens: 8192

    nats:
      url: "nats://nats:4222"
      credentials_file: "/etc/nats/credentials"
      tls:
        enabled: true
        cert_file: "/etc/alchemist/certs/client-cert.pem"
        key_file: "/etc/alchemist/certs/client-key.pem"
        ca_file: "/etc/alchemist/certs/ca.pem"
      jetstream:
        enabled: true
      subjects:
        commands: "cim.agent.alchemist.commands"
        queries: "cim.agent.alchemist.queries"
        events: "cim.agent.alchemist.events"
        dialogs: "cim.dialog.alchemist"
        health: "cim.agent.alchemist.health"

    service:
      port: 8080
      health_check_port: 8081
      metrics_port: 9090
      max_concurrent_requests: 100
      request_timeout: 300
      
    database:
      url: "${DATABASE_URL}"
      max_connections: 50
      
    cache:
      type: "redis"
      redis:
        url: "${REDIS_URL}"
        
    logging:
      level: "${LOG_LEVEL}"
      format: "json"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alchemist-scripts
  namespace: alchemist
  labels:
    app: alchemist
    component: scripts
data:
  startup.sh: |
    #!/bin/bash
    set -e
    
    echo "Starting Alchemist agent..."
    echo "Pod Name: ${POD_NAME}"
    echo "Namespace: ${POD_NAMESPACE}"
    
    # Wait for dependencies
    until nc -z nats 4222; do
      echo "Waiting for NATS..."
      sleep 2
    done
    
    until nc -z postgres 5432; do
      echo "Waiting for PostgreSQL..."
      sleep 2
    done
    
    until nc -z redis 6379; do
      echo "Waiting for Redis..."
      sleep 2
    done
    
    # Run migrations
    echo "Running database migrations..."
    /app/alchemist migrate
    
    # Start the service
    exec /app/alchemist --config /config/config.yaml