# Updated configuration based on bevy-linking.md guide
# Optimized linker configuration for Bevy 0.16 on NixOS

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=mold",
  "-C", "link-arg=-Wl,-rpath,/nix/store/*/lib",
  "-Zshare-generics=y",
]

[build]
target = "x86_64-unknown-linux-gnu"
rustflags = ["--cfg", "edition2024_preview"]

# Development profile optimizations
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (excluding code you're developing locally)
[profile.dev.package."*"]
opt-level = 3

# Enable dynamic linking for tests to resolve experimental occlusion culling issues
[profile.test]
opt-level = 0

# Test environment configuration
[env]
BEVY_HEADLESS = "1"
RUST_BACKTRACE = "1"
